name: sample-rails-with-db
services:
- name: web
  github:
    repo: snormore/sample-rails
    branch: master
  envs:
  - key: DATABASE_URL
    value: ${db.DATABASE_URL}
  - key: RAILS_SERVE_STATIC_FILES
    value: '1'
  - key: RAILS_ENV
    value: production
  run_command: bin/rails db:setup && bin/rails server
databases:
- name: db
  engine: PG
  version: "12"
