default: &default
  adapter: <%= ENV["DB_ADAPTER"] || "postgresql" %>
  encoding: unicode
  pool: <%= ENV["DB_POOL"] || ENV["RAILS_MAX_THREADS"] || 5 %>
  timeout: 5000
  username: postgres
  host: localhost
  port: 5432

development:
  <<: *default
  url: <%= ENV["DATABASE_URL"] %>
  database: <%= ENV.fetch("DATABASE_NAME", File.basename(Rails.root)) %>_dev

test:
  <<: *default
  database: <%= ENV.fetch("DATABASE_NAME", File.basename(Rails.root)) %>_test

production:
  <<: *default
  url: <%= ENV["DATABASE_URL"] %>
